[package]
name = "syzygy"
version = "0.1.0"
authors = ["Alex O'Brien <alex@emobrien.com>"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[dependencies]
volatile = "*"
spin = "*"
lazy_static = { version = "*", features = ["spin_no_std"] }

[profile.release]
lto = "true"
