[package]
name = "initramfs"
version = "0.1.0"
authors = ["3541 <alex@emobrien.com>"]
edition = "2018"


[dependencies]
syzygy = { version = "*", path = "../kernel", optional = true }
hashbrown = { version = "*", features = ["nightly"] }

[features]
kernel = ["syzygy"]
