[alias]
xtask = "run -p xtask --"
x = "run -p xtask --"

[target.'cfg(target_arch = "x86_64")']
rustflags = ["--cfg", 'getrandom_backend="rdrand"']
[target.'cfg(target_arch = "aarch64")']
rustflags = ["--cfg", 'getrandom_backend="rndr"']
