[package]
name = "sz-efi"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
r-efi = "6.0.0"
ucs2 = "0.3.3"
blake2.workspace = true
hex = { version = "0.4.3", default-features = false }
elf.workspace = true
rand = { version = "0.10.0", default-features = false, features = ["sys_rng"] }
getrandom = { version = "0.4.2", default-features = false }
arrayvec = { version = "0.7.4", default-features = false }
common.path = "../../common"
bitflags.workspace = true
