# Build all image components. Include master branch once scratch is merged.

name: build

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rust-src, miri

      - name: deps
        run: stack install shake
        
      - name: build
        run: stack exec -- shake build

      - name: test
        run: |
          stack exec -- shake kernelTest
          stack exec -- shake kernelMiriTest
